In [67]:
import numpy as np
import pandas as pd
import collections
from random import shuffle, randint

from sklearn.cross_validation import train_test_split
from sklearn import svm
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [68]:
#read in csv file
data = pd.read_csv("processed.cleveland.csv", header=None)
trainPercent = 30 #must be between 0 and 100
validationPercent = 35
numberRowsOf0 = 164
numberRowsOf1 = 55
numberRowsOf2 = 36
numberRowsOf3 = 35
numberRowsOf4 = 13
data.head() #look at first 5 rows of the data

0   1   2    3    4   5   6    7   8    9   10   11   12  13
0  63   1   1  145  233   1   2  150   0  2.3   3  0.0  6.0   0
1  67   1   4  160  286   0   2  108   1  1.5   2  3.0  3.0   2
2  67   1   4  120  229   0   2  129   1  2.6   2  2.0  7.0   1
3  37   1   3  130  250   0   0  187   0  3.5   3  0.0  3.0   0
4  41   0   2  130  204   0   2  172   0  1.4   1  0.0  3.0   0

In [69]:
#Grab desired inputs to test one. Build a dataframe from them.
dataInputs= data.loc[:,0:12]
dataInputs.head()

0   1   2    3    4   5   6    7   8    9   10   11   12
0  63   1   1  145  233   1   2  150   0  2.3   3  0.0  6.0
1  67   1   4  160  286   0   2  108   1  1.5   2  3.0  3.0
2  67   1   4  120  229   0   2  129   1  2.6   2  2.0  7.0
3  37   1   3  130  250   0   0  187   0  3.5   3  0.0  3.0
4  41   0   2  130  204   0   2  172   0  1.4   1  0.0  3.0

In [70]:
y1=[]
y2=[]
y3=[]
y4=[]
y5=[]
for i in range(0,numberRowsOf0):
    y1.append([1,0,0,0,0]);#Zero
for i in range(0,numberRowsOf1):
    y2.append([0,1,0,0,0]);#One
for i in range(0,numberRowsOf2):
    y3.append([0,0,1,0,0]);#Second
for i in range(0,numberRowsOf3):
    y4.append([0,0,0,1,0]);#Three
for i in range(0,numberRowsOf4):
    y5.append([0,0,0,0,1]);#Four
expectedOutput=np.concatenate([y1,y2,y3,y4,y5])

In [71]:
#Hint: use train_test_split
inputTrain, inputTest, expectedOutputTrain, expectedOutputTest = train_test_split(dataInputs, expectedOutput, train_size = trainPercent/100, random_state=42)
validateTest, inputTrain, validateOutputTest, expectedOutputTrain = train_test_split(inputTrain, expectedOutputTrain, train_size = validationPercent/100, random_state=42)
#inputTest.head()
print(validateTest.shape)
print(validateOutputTest.shape)
print(inputTrain.shape)
print(expectedOutputTrain.shape)
print(inputTest.shape)
print(expectedOutputTest.shape)

def getClassCountTotals(output):
    d = collections.OrderedDict()
    for a in output:
        t = tuple(a)
        if t in d:
            d[t] += 1
        else:
            d[t] = 1

    result = []
    for (key, value) in d.items():
        result.append(list(key) + [value])

    B = np.asarray(result)
    print(B)
    for Bi in B:
        if Bi[0] == 1:
            zeroTotal = Bi[5]
        elif Bi[1] == 1:
            oneTotal = Bi[5]
        elif Bi[2] == 1:
            twoTotal = Bi[5]
        elif Bi[3] == 1:
            threeTotal = Bi[5]
        elif Bi[4] == 1:
            fourTotal = Bi[5]
            
    return zeroTotal, oneTotal, twoTotal, threeTotal, fourTotal
print(expectedOutputTest)
print("ValidateTest",validateOutputTest)
zeroTotal, oneTotal, twoTotal, threeTotal, fourTotal = getClassCountTotals(expectedOutputTest)
validationCounts = getClassCountTotals(validateOutputTest)
print(zeroTotal)
print(oneTotal)
print(twoTotal)
print(threeTotal)
print(fourTotal)

(31, 13)
(31, 5)
(59, 13)
(59, 5)
(213, 13)
(213, 5)
[[0 1 0 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 ..., 
 [0 0 1 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]]
ValidateTest [[1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 1 0]]
[[  0   1   0   0   0  39]
 [  0   0   1   0   0  28]
 [  1   0   0   0   0 115]
 [  0   0   0   1   0  24]
 [  0   0   0   0   1   7]]
[[ 1  0  0  0  0 17]
 [ 0  0  0  1  0  3]
 [ 0  0  0  0  1  2]
 [ 0  1  0  0  0  6]
 [ 0  0  1  0  0  3]]
115
39
28
24
7


In [72]:
#Build our least squares classifier for 2 classes
D = inputTrain.shape[1] + 1 #num of attributes, +1 is for the intercept (column of 1s)
K = expectedOutput.shape[1]

In [73]:
expectedOutputTrain = np.asarray(expectedOutputTrain)
expectedOutputTest = np.asarray(expectedOutputTest)
inputTrain = np.asarray(inputTrain)
inputTest = np.asarray(inputTest)
validateTest = np.asarray(validateTest)
validateOutputTest = np.asarray(validateOutputTest)

In [74]:
sum1 = 0
sum2 = 0
def createWeightMatrix(x, y, lmbda):
    numRows = x.shape[0]
    new_col = np.ones((numRows,1))
    augmentedX = np.c_[new_col, x]
    sum1 = np.dot(augmentedX.T, augmentedX) + lmbda
    sum2 = np.dot(augmentedX.T, y)
    W = np.dot(np.linalg.inv(sum1), sum2)
    return W

In [75]:
def classificationTest(xTest, yTest, W, isValidating):  
    returnVals = []
    total = yTest.shape[0]
    predicted = np.zeros((total, K))
    i=0
    zeroCorrect=oneCorrect=twoCorrect=threeCorrect=fourCorrect=totalCorrect=0
    correctPredictionCol = [0]*total
    for i in range(total):      
        x = xTest[i]        
        x = np.append(1,x)         
        x = x.reshape(1,D)        
        values = np.dot(W.T,x.T)
        values = values.T
        values = values.flatten()
        maxIndex = np.argmax(values)
        if yTest[i][maxIndex] == 1:
            if maxIndex == 0:
                zeroCorrect += 1
            elif maxIndex == 1:
                oneCorrect += 1
            elif maxIndex == 2:
                twoCorrect += 1
            elif maxIndex == 3:
                threeCorrect +=1
            elif maxIndex == 4:
                fourCorrect +=1
            correctPredictionCol[i] = 1
        predicted[i][maxIndex] = 1
    totalCorrect = zeroCorrect + oneCorrect + twoCorrect + threeCorrect + fourCorrect
    print(totalCorrect)
    totalAccuracy=totalCorrect/float(total)*100
    if isValidating == False:
        zeroAccuracy = zeroCorrect/float(zeroTotal)*100
        oneAccuracy = oneCorrect/float(oneTotal)*100
        twoAccuracy = twoCorrect/float(twoTotal)*100
        threeAccuracy = threeCorrect/float(threeTotal)*100
        fourAccuracy = fourCorrect/float(fourTotal)*100
        print("zero misclassification error = ", 100 - zeroAccuracy)
        print("one misclassification error = ", 100 - oneAccuracy)
        print("two misclassification error = ", 100 - twoAccuracy)
        print("three misclassification error = ", 100 - threeAccuracy)
        print("four misclassification error = ", 100 - fourAccuracy)
    else:
        zeroAccuracy = zeroCorrect/float(validationCounts[0])*100
        oneAccuracy = oneCorrect/float(validationCounts[1])*100
        twoAccuracy = twoCorrect/float(validationCounts[2])*100
        threeAccuracy = threeCorrect/float(validationCounts[3])*100
        fourAccuracy = fourCorrect/float(validationCounts[4])*100
        print("zero misclassification error = ", 100 - zeroAccuracy)
        print("one misclassification error = ", 100 - oneAccuracy)
        print("two misclassification error = ", 100 - twoAccuracy)
        print("three misclassification error = ", 100 - threeAccuracy)
        print("four misclassification error = ", 100 - fourAccuracy)
    print("total misclassification error = ", 100 - totalAccuracy)
    print(total)
    returnVals.append(100-totalAccuracy)
    returnVals.append(predicted)
    returnVals.append(correctPredictionCol)
    return returnVals

In [76]:
#cross validation
lambdaValues = [100000, 100, 0,.1 , .3, .01, .03, .001, .003, .0001, .0003]
lambdaIndexOfMinError = -1
minError = 101
i = 0
for l in lambdaValues :
    print("lambda val?",l)
    W=0
    W = createWeightMatrix(inputTrain, expectedOutputTrain, l)
    print("W",W)
    error, predictedClasses, correctPredCol = classificationTest(validateTest, validateOutputTest, W, True)
    print("error ",error)    
    if(error < minError):
        minError = error
        lambdaIndexOfMinError = i
    i+=1
print("smalled index of error for lambda...", lambdaIndexOfMinError)

Wtest = createWeightMatrix(inputTrain, expectedOutputTrain, lambdaValues[lambdaIndexOfMinError])

lambda val? 100000
W [[ nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan]]
17
zero misclassification error =  0.0
one misclassification error =  100.0
two misclassification error =  100.0
three misclassification error =  100.0
four misclassification error =  100.0
total misclassification error =  45.16129032258065
31
error  45.16129032258065
lambda val? 100
W [[ nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan]
 [ nan  nan  nan  n

In [77]:
#testing
error, predictedClasses, correctPredictionCol = classificationTest(inputTest, expectedOutputTest, Wtest, False)
print(error)

115
zero misclassification error =  0.0
one misclassification error =  100.0
two misclassification error =  100.0
three misclassification error =  100.0
four misclassification error =  100.0
total misclassification error =  46.009389671361504
213
46.009389671361504
