In [590]:
import numpy as np
import pandas as pd
import collections
from random import shuffle, randint

from sklearn.cross_validation import train_test_split
from sklearn import svm
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [591]:
#read in csv file
data = pd.read_csv("space.csv", header=None)
trainPercent = 50 #must be between 0 and 100
st = randint(0,10000)
print(st)
validationPercent = 25
numberRowsOfRedSoil = data.loc[data[36] == 1].shape[0]
numberRowsOfCottonCrop = data.loc[data[36] == 2].shape[0]
numberRowsOfGreySoil = data.loc[data[36] == 3].shape[0]
numberRowsOfDampGreySoil = data.loc[data[36] == 4].shape[0]
numberRowsOfSoilWithVS = data.loc[data[36] == 5].shape[0]
numberRowsOfVeryDampGreySoil = data.loc[data[36] == 7].shape[0]
data.head() #look at first 5 rows of the data

9871


0    1    2   3   4    5    6   7   8    9  ...  27  28   29   30  31  32  \
0  80  102  102  79  76  102  102  79  76  102 ...  87  79  107  109  87  79   
1  76  102  102  79  76  102  106  83  76  102 ...  87  79  107  113  87  79   
2  80   98  106  79  76   94  102  76  76   94 ...  79  79   95  100  79  79   
3  76   94  102  76  76   94  102  76  76   94 ...  79  79   95   96  75  79   
4  76   94  102  76  76   94  102  76  76   89 ...  75  79   95  100  75  75   

    33   34  35  36  
0  107  113  87   3  
1  103  104  83   3  
2   95   96  75   4  
3   95  100  75   4  
4   95  100  79   4  

[5 rows x 37 columns]

In [592]:
dataInputs= data.loc[:,0:35]
dataInputs.head()

0    1    2   3   4    5    6   7   8    9  ...   26  27  28   29   30  31  \
0  80  102  102  79  76  102  102  79  76  102 ...  109  87  79  107  109  87   
1  76  102  102  79  76  102  106  83  76  102 ...  109  87  79  107  113  87   
2  80   98  106  79  76   94  102  76  76   94 ...  104  79  79   95  100  79   
3  76   94  102  76  76   94  102  76  76   94 ...  100  79  79   95   96  75   
4  76   94  102  76  76   94  102  76  76   89 ...   96  75  79   95  100  75   

   32   33   34  35  
0  79  107  113  87  
1  79  103  104  83  
2  79   95   96  75  
3  79   95  100  75  
4  75   95  100  79  

[5 rows x 36 columns]

In [593]:
y1=[]
y2=[]
y3=[]
y5=[]
y6=[]
y7=[]
for i in range(0,numberRowsOfRedSoil):
    y1.append([1,0,0,0,0,0]);#BuildingWindowsFP
for i in range(0,numberRowsOfCottonCrop):
    y2.append([0,1,0,0,0,0]);#BuildingWindowsNFP
for i in range(0,numberRowsOfGreySoil):
    y3.append([0,0,1,0,0,0]);#VehicleWindowsFP
for i in range(0,numberRowsOfDampGreySoil):
    y5.append([0,0,0,1,0,0]);#Containers
for i in range(0,numberRowsOfSoilWithVS):
    y6.append([0,0,0,0,1,0]);#Tableware
for i in range(0,numberRowsOfVeryDampGreySoil):
    y7.append([0,0,0,0,0,1]);#Lamps
expectedOutput=np.concatenate([y1,y2,y3,y5,y6,y7])

In [594]:
#Hint: use train_test_split
inputTrain, inputTest, expectedOutputTrain, expectedOutputTest = train_test_split(dataInputs, expectedOutput, train_size = trainPercent/100, random_state=st)
validateTest, inputTrain, validateOutputTest, expectedOutputTrain = train_test_split(inputTrain, expectedOutputTrain, train_size = validationPercent/100, random_state=st)
#inputTest.head()
print(validateTest.shape)
print(validateOutputTest.shape)
print(inputTrain.shape)
print(expectedOutputTrain.shape)
print(inputTest.shape)
print(expectedOutputTest.shape)

def getClassCountTotals(output):
    d = collections.OrderedDict()
    for a in output:
        t = tuple(a)
        if t in d:
            d[t] += 1
        else:
            d[t] = 1

    result = []
    for (key, value) in d.items():
        result.append(list(key) + [value])

    B = np.asarray(result)
    print(B)
    for Bi in B:
        print("B", B)
        if Bi[0] == 1:
            redSoilTotal = Bi[6]
        elif Bi[1] == 1:
            cottonCropTotal = Bi[6]
        elif Bi[2] == 1:
            greySoilTotal = Bi[6]
        elif Bi[3] == 1:
            dampGreySoilTotal = Bi[6]
        elif Bi[4] == 1:
            soilWithVSTotal = Bi[6]
        elif Bi[5] == 1:
            veryDampGreySoilTotal = Bi[6]
            
    return redSoilTotal, cottonCropTotal, greySoilTotal, dampGreySoilTotal, soilWithVSTotal, veryDampGreySoilTotal
print(expectedOutputTest)
print("ValidateTest",validateOutputTest)
redSoilTotal, cottonCropTotal, greySoilTotal, dampGreySoilTotal, soilWithVSTotal, veryDampGreySoilTotal = getClassCountTotals(expectedOutputTest)
print("validate output test", validateOutputTest)
validationCounts = getClassCountTotals(validateOutputTest)
print(redSoilTotal)
print(cottonCropTotal)
print(greySoilTotal)
print(dampGreySoilTotal)
print(soilWithVSTotal)
print(veryDampGreySoilTotal)

(250, 36)
(250, 6)
(750, 36)
(750, 6)
(1000, 36)
(1000, 6)
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 0 1]
 ..., 
 [1 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]
ValidateTest [[0 0 0 0 0 1]
 [0 0 1 0 0 0]
 [0 0 0 0 0 1]
 ..., 
 [0 0 0 1 0 0]
 [0 0 0 0 0 1]
 [0 0 0 1 0 0]]
[[  1   0   0   0   0   0 225]
 [  0   1   0   0   0   0 124]
 [  0   0   0   0   0   1 232]
 [  0   0   0   1   0   0 124]
 [  0   0   1   0   0   0 185]
 [  0   0   0   0   1   0 110]]
B [[  1   0   0   0   0   0 225]
 [  0   1   0   0   0   0 124]
 [  0   0   0   0   0   1 232]
 [  0   0   0   1   0   0 124]
 [  0   0   1   0   0   0 185]
 [  0   0   0   0   1   0 110]]
B [[  1   0   0   0   0   0 225]
 [  0   1   0   0   0   0 124]
 [  0   0   0   0   0   1 232]
 [  0   0   0   1   0   0 124]
 [  0   0   1   0   0   0 185]
 [  0   0   0   0   1   0 110]]
B [[  1   0   0   0   0   0 225]
 [  0   1   0   0   0   0 124]
 [  0   0   0   0   0   1 232]
 [  0   0   0   1   0   0 124]
 [  0   0   1   0   0   0 185]
 [  0   0 

In [595]:
#Build our least squares classifier for 2 classes
D = inputTrain.shape[1] + 1 #num of attributes, +1 is for the intercept (column of 1s)
K = expectedOutput.shape[1]

In [596]:
expectedOutputTrain = np.asarray(expectedOutputTrain)
expectedOutputTest = np.asarray(expectedOutputTest)
inputTrain = np.asarray(inputTrain)
inputTest = np.asarray(inputTest)
validateTest = np.asarray(validateTest)
validateOutputTest = np.asarray(validateOutputTest)

In [597]:
sum1 = 0
sum2 = 0
def createWeightMatrix(x, y, lmbda):
    numRows = x.shape[0]
    new_col = np.ones((numRows,1))
    augmentedX = np.c_[new_col, x]
    sum1 = np.dot(augmentedX.T, augmentedX) + lmbda
    sum2 = np.dot(augmentedX.T, y)
    W = np.dot(np.linalg.inv(sum1), sum2)
    return W

In [598]:
def classificationTest(xTest, yTest, W, isValidating):  
    returnVals = []
    total = yTest.shape[0]
    predicted = np.zeros((total, K))
    i=0
    redSoilCorrect=cottonCropCorrect=greySoilCorrect=dampGreySoilCorrect=soilWithVSCorrect=veryDampGreySoilCorrect=totalCorrect=0
    correctPredictionCol = [0]*total
    for i in range(total):      
        x = xTest[i]        
        x = np.append(1,x)         
        x = x.reshape(1,D)        
        values = np.dot(W.T,x.T)
        values = values.T
        values = values.flatten()
        maxIndex = np.argmax(values)
        if yTest[i][maxIndex] == 1:
            if maxIndex == 0:
                redSoilCorrect += 1
            elif maxIndex == 1:
                cottonCropCorrect += 1
            elif maxIndex == 2:
                greySoilCorrect += 1
            elif maxIndex == 3:
                dampGreySoilCorrect +=1
            elif maxIndex == 4:
                soilWithVSCorrect +=1
            elif maxIndex == 5:
                veryDampGreySoilCorrect +=1
            correctPredictionCol[i] = 1
        predicted[i][maxIndex] = 1
    totalCorrect =redSoilCorrect+cottonCropCorrect+greySoilCorrect+dampGreySoilCorrect+soilWithVSCorrect+veryDampGreySoilCorrect
    print(totalCorrect)
    totalAccuracy=totalCorrect/float(total)*100
    if isValidating == False:
        redSoilAccuracy = redSoilCorrect/float(redSoilTotal)*100
        cottonCropAccuracy = cottonCropCorrect/float(cottonCropTotal)*100
        greySoilAccuracy = greySoilCorrect/float(greySoilTotal)*100
        dampGreySoilAccuracy = dampGreySoilCorrect/float(dampGreySoilTotal)*100
        soilWithVSAccuracy = soilWithVSCorrect/float(soilWithVSTotal)*100
        veryDampGreySoilAccuracy = veryDampGreySoilCorrect/float(veryDampGreySoilTotal)*100
        print("redSoil misclassification error = ", 100 - redSoilAccuracy)
        print("cottonCrop misclassification error = ", 100 - cottonCropAccuracy)
        print("greySoil misclassification error = ", 100 - greySoilAccuracy)
        print("dampGreySoil misclassification error = ", 100 - dampGreySoilAccuracy)
        print("soilWithVS misclassification error = ", 100 - soilWithVSAccuracy)
        print("veryDampGreySoil misclassification error = ", 100 - veryDampGreySoilAccuracy)
    else:
        redSoilAccuracy = redSoilCorrect/float(validationCounts[0])*100
        cottonCropAccuracy = cottonCropCorrect/float(validationCounts[1])*100
        greySoilAccuracy = greySoilCorrect/float(validationCounts[2])*100
        dampGreySoilAccuracy = dampGreySoilCorrect/float(validationCounts[3])*100
        soilWithVSAccuracy = soilWithVSCorrect/float(validationCounts[4])*100
        veryDampGreySoilAccuracy = veryDampGreySoilCorrect/float(validationCounts[5])*100
        print("redSoil misclassification error = ", 100 - redSoilAccuracy)
        print("cottonCrop misclassification error = ", 100 - cottonCropAccuracy)
        print("greySoil misclassification error = ", 100 - greySoilAccuracy)
        print("dampGreySoil misclassification error = ", 100 - dampGreySoilAccuracy)
        print("soilWithVS misclassification error = ", 100 - soilWithVSAccuracy)
        print("veryDampGreySoil misclassification error = ", 100 - veryDampGreySoilAccuracy)
    print("total misclassification error = ", 100 - totalAccuracy)
    print(total)
    returnVals.append(100-totalAccuracy)
    returnVals.append(predicted)
    returnVals.append(correctPredictionCol)
    return returnVals

In [599]:
#cross validation
lambdaValues = [0, 100, 1000000,.1 , .3, .01, .03, .001, .003, .0001, .0003]
lambdaIndexOfMinError = -1
minError = 101
i = 0
for l in lambdaValues :
    print("lambda val?",l)
    W=0
    W = createWeightMatrix(inputTrain, expectedOutputTrain, l)
    print("W",W)
    error, predictedClasses, correctPredCol = classificationTest(validateTest, validateOutputTest, W, True)
    print("error ",error)    
    if(error < minError):
        minError = error
        lambdaIndexOfMinError = i
    i+=1
print("smallest index of error for lambda...", lambdaIndexOfMinError)

Wtest = createWeightMatrix(inputTrain, expectedOutputTrain, lambdaValues[lambdaIndexOfMinError])

lambda val? 0
W [[ -1.28141186e+00   2.68008180e-01   8.08977778e-01   3.01250544e-01
    2.43338222e-01   6.59837141e-01]
 [  1.03918157e-02   3.66744507e-03  -2.53289404e-04   2.30351785e-03
   -1.37515587e-03  -1.47343334e-02]
 [ -6.37505173e-04  -4.98313597e-03  -4.14949666e-03  -3.74868957e-03
    6.74552054e-05   1.34513722e-02]
 [  1.75522443e-03   2.59061550e-03  -4.52665150e-03  -5.82211805e-04
    6.34665295e-03  -5.58362958e-03]
 [  3.64361649e-03  -7.70124479e-03   9.42635242e-03  -6.19666832e-04
   -9.27152366e-03   4.52246637e-03]
 [ -3.35549947e-03  -2.86391511e-04  -3.11410212e-04  -1.56109935e-04
    5.49798808e-03  -1.38857695e-03]
 [ -2.45237843e-03   5.72364812e-03   1.02376193e-03   1.80034445e-04
   -3.18109205e-03  -1.29397401e-03]
 [  3.25742135e-03  -7.67662790e-04   1.34619617e-04   7.19503790e-03
   -3.79770476e-03  -6.02171133e-03]
 [ -7.88687394e-03   8.40853542e-03  -8.79543695e-03  -3.63951623e-03
    4.90817006e-03   7.00512165e-03]
 [  6.81257318e-03  -

In [600]:
#testing
error, predictedClasses, correctPredictionCol = classificationTest(inputTest, expectedOutputTest, Wtest, False)
print(error)

424
redSoil misclassification error =  27.555555555555557
cottonCrop misclassification error =  90.3225806451613
greySoil misclassification error =  42.16216216216216
dampGreySoil misclassification error =  100.0
soilWithVS misclassification error =  99.0909090909091
veryDampGreySoil misclassification error =  39.224137931034484
total misclassification error =  57.6
1000
57.6


In [601]:
actual = pd.DataFrame(expectedOutputTest)
predictedDF = pd.DataFrame(predictedClasses)
correct = pd.DataFrame(correctPredictionCol)
frames = [predictedDF, actual, correct]
modelTest = pd.concat(frames, axis=1)
modelTest.columns = ["Predicted","Predicted", "Predicted", "Predicted", "Predicted", "Predicted", "Actual", "Actual", "Actual", "Actual", "Actual", "Actual", "Correct"]
modelTest

Predicted  Predicted  Predicted  Predicted  Predicted  Predicted  Actual  \
0          1.0        0.0        0.0        0.0        0.0        0.0       1   
1          0.0        0.0        1.0        0.0        0.0        0.0       0   
2          0.0        0.0        0.0        0.0        0.0        1.0       0   
3          0.0        0.0        0.0        0.0        0.0        1.0       0   
4          0.0        0.0        0.0        0.0        1.0        0.0       0   
5          0.0        0.0        1.0        0.0        0.0        0.0       0   
6          0.0        0.0        1.0        0.0        0.0        0.0       0   
7          0.0        0.0        0.0        0.0        0.0        1.0       0   
8          0.0        0.0        1.0        0.0        0.0        0.0       0   
9          1.0        0.0        0.0        0.0        0.0        0.0       1   
10         1.0        0.0        0.0        0.0        0.0        0.0       1   
11         1.0        0.0        0.0        0.0        0.0        0.0       0   
12         1.0        0.0        0.0        0.0        0.0        0.0       1   
13         0.0        0.0        0.0        0.0        1.0        0.0       0   
14         0.0        0.0        1.0        0.0        0.0        0.0       0   
15         0.0        0.0        1.0        0.0        0.0        0.0       0   
16         1.0        0.0        0.0        0.0        0.0        0.0       0   
17         0.0        0.0        1.0        0.0        0.0        0.0       0   
18         0.0        0.0        0.0        0.0        0.0        1.0       0   
19         1.0        0.0        0.0        0.0        0.0        0.0       0   
20         0.0        0.0        1.0        0.0        0.0        0.0       0   
21         1.0        0.0        0.0        0.0        0.0        0.0       1   
22         1.0        0.0        0.0        0.0        0.0        0.0       0   
23         0.0        0.0        1.0        0.0        0.0        0.0       0   
24         1.0        0.0        0.0        0.0        0.0        0.0       0   
25         1.0        0.0        0.0        0.0        0.0        0.0       0   
26         0.0        1.0        0.0        0.0        0.0        0.0       0   
27         0.0        0.0        0.0        0.0        0.0        1.0       0   
28         0.0        0.0        1.0        0.0        0.0        0.0       0   
29         1.0        0.0        0.0        0.0        0.0        0.0       1   
..         ...        ...        ...        ...        ...        ...     ...   
970        1.0        0.0        0.0        0.0        0.0        0.0       1   
971        0.0        0.0        1.0        0.0        0.0        0.0       0   
972        0.0        0.0        1.0        0.0        0.0        0.0       0   
973        0.0        1.0        0.0        0.0        0.0        0.0       0   
974        0.0        0.0        0.0        0.0        0.0        1.0       0   
975        0.0        0.0        0.0        0.0        1.0        0.0       1   
976        1.0        0.0        0.0        0.0        0.0        0.0       0   
977        1.0        0.0        0.0        0.0        0.0        0.0       0   
978        0.0        0.0        1.0        0.0        0.0        0.0       0   
979        0.0        0.0        0.0        0.0        0.0        1.0       0   
980        0.0        0.0        1.0        0.0        0.0        0.0       1   
981        0.0        0.0        0.0        0.0        0.0        1.0       0   
982        0.0        0.0        0.0        0.0        0.0        1.0       0   
983        0.0        0.0        0.0        0.0        0.0        1.0       0   
984        1.0        0.0        0.0        0.0        0.0        0.0       0   
985        0.0        0.0        1.0        0.0        0.0        0.0       0   
986        1.0        0.0        0.0        0.0        0.0        0.0       1   
987        1.0        0.0        0.0

In [602]:
actualAsClassNumber = [0]*expectedOutputTest.shape[0]
predictedAsClassNumber = [0]*expectedOutputTest.shape[0]
for i in range(expectedOutputTest.shape[0]):
    actualAsClassNumber[i] = expectedOutputTest[i].tolist().index(1)
    predictedAsClassNumber[i] = predictedClasses[i].tolist().index(1.0)
confusion_matrix(actualAsClassNumber, predictedAsClassNumber)

array([[163,   1,  50,   0,   3,   8],
       [ 50,  12,  58,   0,   2,   2],
       [ 54,   4, 107,   0,   2,  18],
       [ 25,   1,  56,   0,   5,  37],
       [ 20,   1,  32,   0,   1,  56],
       [ 51,   0,  33,   0,   7, 141]])

In [603]:
clf = svm.SVC(kernel='linear', C=1)
expectedOutputSVM = data.loc[:,36]
inputTrain, inputTest, expectedOutputTrain, expectedOutputTest = train_test_split(dataInputs, expectedOutputSVM, train_size = trainPercent/100, random_state=st)
clf.fit(inputTrain, expectedOutputTrain)
accuracy = clf.score(inputTest, expectedOutputTest)
print(accuracy)

0.809


In [604]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.multiclass import OneVsRestClassifier

In [605]:
#SVM One vs all classifier
clf = Pipeline([
    ('clf', OneVsRestClassifier(LinearSVC()))])
model = clf.fit(inputTrain, expectedOutputTrain)
accuracy = clf.score(inputTest, expectedOutputTest)
print(accuracy)
svmPredicted = model.predict(inputTest)
confusion_matrix(expectedOutputTest,svmPredicted)

0.719


array([[238,   0,   0,   0,   0,   0],
       [  2,  86,   1,   0,  12,   0],
       [ 18,   0, 126,   0,   5,  43],
       [  1,   1,  47,   4,   8,  55],
       [ 16,   6,   0,   1,  88,  16],
       [  1,   3,  27,   1,  17, 177]])