In [45]:
import numpy as np
import pandas as pd
import collections
from random import shuffle, randint

from sklearn.cross_validation import train_test_split
from sklearn import svm
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [46]:
#read in csv file
data = pd.read_csv("glass.csv", header=None)
trainPercent = 30 #must be between 0 and 100
validationPercent = 35
numberRowsOfBuildingWindowsFP = 70
numberRowsOfBuildingWindowsNFP = 76
numberRowsOfVehicleWindowsFP = 17
numberRowsOfVehicleWindowsNFP = 0
numberRowsOfContainers = 13
numberRowsOfTableware = 9
numberRowsOfLamps = 29
data.head() #look at first 5 rows of the data

0        1      2     3     4      5     6     7    8    9   10
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0   1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0   1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0   1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0   1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0   1

In [47]:
dataInputs= data.loc[:,0:9]
dataInputs.head()

0        1      2     3     4      5     6     7    8    9
0  1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0
1  2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0
2  3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0
3  4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0
4  5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0

In [48]:
y1=[]
y2=[]
y3=[]
y5=[]
y6=[]
y7=[]
for i in range(0,numberRowsOfBuildingWindowsFP):
    y1.append([1,0,0,0,0,0]);#BuildingWindowsFP
for i in range(0,numberRowsOfBuildingWindowsNFP):
    y2.append([0,1,0,0,0,0]);#BuildingWindowsNFP
for i in range(0,numberRowsOfVehicleWindowsFP):
    y3.append([0,0,1,0,0,0]);#VehicleWindowsFP
for i in range(0,numberRowsOfContainers):
    y5.append([0,0,0,1,0,0]);#Containers
for i in range(0,numberRowsOfTableware):
    y6.append([0,0,0,0,1,0]);#Tableware
for i in range(0,numberRowsOfLamps):
    y7.append([0,0,0,0,0,1]);#Lamps
expectedOutput=np.concatenate([y1,y2,y3,y5,y6,y7])

In [49]:
#Hint: use train_test_split
inputTrain, inputTest, expectedOutputTrain, expectedOutputTest = train_test_split(dataInputs, expectedOutput, train_size = trainPercent/100, random_state=42)
validateTest, inputTrain, validateOutputTest, expectedOutputTrain = train_test_split(inputTrain, expectedOutputTrain, train_size = validationPercent/100, random_state=42)
#inputTest.head()
print(validateTest.shape)
print(validateOutputTest.shape)
print(inputTrain.shape)
print(expectedOutputTrain.shape)
print(inputTest.shape)
print(expectedOutputTest.shape)

def getClassCountTotals(output):
    vehicleWindowsFPTotal = 0
    d = collections.OrderedDict()
    for a in output:
        t = tuple(a)
        if t in d:
            d[t] += 1
        else:
            d[t] = 1

    result = []
    for (key, value) in d.items():
        result.append(list(key) + [value])

    B = np.asarray(result)
    print(B)
    for Bi in B:
        if Bi[0] == 1:
            buildingWindowsFPTotal = Bi[6]
        elif Bi[1] == 1:
            buildingWindowsNFPTotal = Bi[6]
        elif Bi[2] == 1:
            vehicleWindowsFPTotal = Bi[6]
        elif Bi[3] == 1:
            containersTotal = Bi[6]
        elif Bi[4] == 1:
            tablewareTotal = Bi[6]
        elif Bi[5] == 1:
            lampTotal = Bi[6]
            
    return buildingWindowsFPTotal, buildingWindowsNFPTotal, vehicleWindowsFPTotal, containersTotal, tablewareTotal, lampTotal
print(expectedOutputTest)
print("ValidateTest",validateOutputTest)
buildingWindowsFPTotal, buildingWindowsNFPTotal, vehicleWindowsFPTotal, containersTotal, tablewareTotal, lampTotal = getClassCountTotals(expectedOutputTest)
validationCounts = getClassCountTotals(validateOutputTest)
print(buildingWindowsFPTotal)
print(buildingWindowsNFPTotal)
print(vehicleWindowsFPTotal)
print(containersTotal)
print(tablewareTotal)
print(lampTotal)

(22, 10)
(22, 6)
(42, 10)
(42, 6)
(150, 10)
(150, 6)
[[1 0 0 0 0 0]
 [0 0 0 0 0 1]
 [1 0 0 0 0 0]
 [0 0 0 0 0 1]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 1 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 1]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 1 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 1 0 0 0]
 [0 1 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 1 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 1 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 1 0 0]
 [0 0 1 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 0 1]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 0 1]
 [0 1 0 0 0 0]
 [0 0 0 1 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [1 0 0 0 0 0]
 [