In [62]:
import numpy as np
import pandas as pd
import collections
from random import shuffle, randint

from sklearn.cross_validation import train_test_split
from sklearn import svm
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [63]:
#read in csv file
data = pd.read_csv("wine.csv", header=None)
trainPercent = 40 #must be between 0 and 100
validationPercent = 35
lmbda = .00001
numberRowsOfClass1 = 59
numberRowsOfClass2 = 71
numberRowsOfClass3 = 48
data.head() #look at first 5 rows of the data

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [64]:
#Grab desired inputs to test one. Build a dataframe from them.
dataInputs= data.loc[:,1:13]
dataInputs.head()

1     2     3     4    5     6     7     8     9     10    11    12  \
0  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [65]:
#Grab the expected outputs. (This is supervised learning)
y1=[]
y2=[]
y3=[]
for i in range(0,numberRowsOfClass1):
    y1.append([1,0,0]);#class1
for j in range(0, numberRowsOfClass2):
    y2.append([0,1,0]);#class2
for k in range(0, numberRowsOfClass3):
    y3.append([0,0,1]);#Class3
expectedOutput=np.concatenate([y1,y2,y3])
expectedOutput

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1,

In [66]:
#Hint: use train_test_split
inputTrain, inputTest, expectedOutputTrain, expectedOutputTest = train_test_split(dataInputs, expectedOutput, train_size = trainPercent/100, random_state=42)
validateTest, inputTrain, validateOutputTest, expectedOutputTrain = train_test_split(inputTrain, expectedOutputTrain, train_size = validationPercent/100, random_state=42)
#inputTest.head()
print(validateTest.shape)
print(validateOutputTest.shape)
print(inputTrain.shape)
print(expectedOutputTrain.shape)
print(inputTest.shape)
print(expectedOutputTest.shape)

def getClassCountTotals(output):
    d = collections.OrderedDict()
    for a in output:
        t = tuple(a)
        if t in d:
            d[t] += 1
        else:
            d[t] = 1

    result = []
    for (key, value) in d.items():
        result.append(list(key) + [value])

    B = np.asarray(result)
    print(B)
    for Bi in B:
        if Bi[0] == 1:
            class1Total = Bi[3]
        elif Bi[1] == 1:
            class2Total = Bi[3]
        elif Bi[2] == 1:
            class3Total = Bi[3]
    return class1Total, class2Total, class3Total
print(expectedOutputTest)
print("ValidateTest",validateOutputTest)
class1Total, class2Total, class3Total = getClassCountTotals(expectedOutputTest)
validationCounts = getClassCountTotals(validateOutputTest)
print(class1Total)
print(class2Total)
print(class3Total)

(24, 13)
(24, 3)
(47, 13)
(47, 3)
(107, 13)
(107, 3)
[[1 0 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [

In [67]:
#Build our least squares classifier for 2 classes
D = inputTrain.shape[1] + 1 #num of attributes, +1 is for the intercept (column of 1s)
K = expectedOutput.shape[1]

In [68]:
expectedOutputTrain = np.asarray(expectedOutputTrain)
expectedOutputTest = np.asarray(expectedOutputTest)
inputTrain = np.asarray(inputTrain)
inputTest = np.asarray(inputTest)
validateTest = np.asarray(validateTest)
validateOutputTest = np.asarray(validateOutputTest)

In [69]:
sum1 = 0
sum2 = 0
def createWeightMatrix(x, y, lmbda):
    numRows = x.shape[0]
    print("y", y)
    new_col = np.ones((numRows,1))
    augmentedX = np.c_[new_col, x]
    sum1 = np.dot(augmentedX.T, augmentedX) + lmbda
    sum2 = np.dot(augmentedX.T, y)
    W = np.dot(np.linalg.inv(sum1), sum2)
    return W

In [70]:
def classificationTest(xTest, yTest, W, isValidating):  
    returnVals = []
    total = yTest.shape[0]
    predicted = np.zeros((total, K))
    i=0
    class1Correct=class2Correct=class3Correct=totalCorrect=0
    correctPredictionCol = [0]*total
    for i in range(total):      
        x = xTest[i]        
        x = np.append(1,x)         
        x = x.reshape(1,D)        
        values = np.dot(W.T,x.T)
        values = values.T
        values = values.flatten()
        maxIndex = np.argmax(values)
        if yTest[i][maxIndex] == 1:
            if maxIndex == 0:
                class1Correct += 1
            elif maxIndex == 1:
                class2Correct += 1
            elif maxIndex == 2:
                class3Correct += 1
            correctPredictionCol[i] = 1
        predicted[i][maxIndex] = 1
    totalCorrect = class1Correct + class2Correct + class3Correct
    print(totalCorrect)
    totalAccuracy=totalCorrect/float(total)*100
    if isValidating == False:
        class1Accuracy = class1Correct/float(class1Total)*100
        class2Accuracy = class2Correct/float(class2Total)*100
        class3Accuracy = class3Correct/float(class3Total)*100
        print("class1 misclassification error = ", 100 - class1Accuracy)
        print("class2 misclassification error = ", 100 - class2Accuracy)
        print("class3 misclassification error = ", 100 - class3Accuracy)
    else:
        class1Accuracy = class1Correct/float(validationCounts[0])*100
        class2Accuracy = class2Correct/float(validationCounts[1])*100
        class3Accuracy = class3Correct/float(validationCounts[2])*100
        print("class1 misclassification error = ", 100 - class1Accuracy)
        print("class2 misclassification error = ", 100 - class2Accuracy)
        print("class3 misclassification error = ", 100 - class3Accuracy)
    print("total misclassification error = ", 100 - totalAccuracy)
    print(total)
    returnVals.append(100-totalAccuracy)
    returnVals.append(predicted)
    returnVals.append(correctPredictionCol)
    return returnVals

In [71]:
#cross validation
lambdaValues = [100000, 100, 0,.1 , .3, .01, .03, .001, .003, .0001, .0003]
lambdaIndexOfMinError = -1
minError = 101
i = 0
for l in lambdaValues :
    print("lambda val?",l)
    W=0
    W = createWeightMatrix(inputTrain, expectedOutputTrain, l)
    print("W",W)
    error, predictedClasses, correctPredCol = classificationTest(validateTest, validateOutputTest, W, True)
    print("error ",error)    
    if(error < minError):
        minError = error
        lambdaIndexOfMinError = i
    i+=1
print("smalled index of error for lambda...", lambdaIndexOfMinError)

Wtest = createWeightMatrix(inputTrain, expectedOutputTrain, lambdaValues[lambdaIndexOfMinError])

lambda val? 100000
y [[0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]]
W [[ -1.38900055e-01   3.49681953e-01  -2.96417900e-01]
 [  1.47943829e-02   1.05644543e-02   3.48165508e-02]
 [  1.51127855e-02  -5.08121062e-02   3.69649467e-02]
 [  3.32101061e-01  -8.21776871e-01   5.02963744e-01]
 [ -6.11401176e-02   1.01922601e-01  -3.02264578e-02]
 [ -2.16808154e-03   8.23348680e-04   2.46015025e-03]
 [ -1.12902368e-01  -1.44617988e-02   1.53621316e-01]
 [  3.78904654e-02   1.31799908e-01  -1.90225154e-01]
 [ -3.94826566e-01   3.82586849e-01  -1.63454655e-02]
 [  3.32432990e-02   2.04072289e-02  -4.12299721e-02]
 [  2.8447794

In [72]:
#testing
error, predictedClasses, correctPredictionCol = classificationTest(inputTest, expectedOutputTest, Wtest, False)
print(error)

101
class1 misclassification error =  0.0
class2 misclassification error =  11.627906976744185
class3 misclassification error =  3.5714285714285694
total misclassification error =  5.607476635514018
107
5.607476635514018


In [73]:
actual = pd.DataFrame(expectedOutputTest)
predictedDF = pd.DataFrame(predictedClasses)
correct = pd.DataFrame(correctPredictionCol)
frames = [predictedDF, actual, correct]
modelTest = pd.concat(frames, axis=1)
modelTest.columns = ["Predicted","Predicted", "Predicted", "Actual", "Actual", "Actual", "Correct"]
modelTest

Predicted  Predicted  Predicted  Actual  Actual  Actual  Correct
0          1.0        0.0        0.0       1       0       0        1
1          1.0        0.0        0.0       1       0       0        1
2          0.0        0.0        1.0       0       0       1        1
3          1.0        0.0        0.0       1       0       0        1
4          0.0        1.0        0.0       0       1       0        1
5          1.0        0.0        0.0       1       0       0        1
6          0.0        1.0        0.0       0       1       0        1
7          0.0        0.0        1.0       0       0       1        1
8          0.0        1.0        0.0       0       1       0        1
9          0.0        0.0        1.0       0       0       1        1
10         1.0        0.0        0.0       1       0       0        1
11         0.0        0.0        1.0       0       0       1        1
12         1.0        0.0        0.0       1       0       0        1
13         0.0        1.0        0.0       0       1       0        1
14         1.0        0.0        0.0       1       0       0        1
15         0.0        1.0        0.0       0       1       0        1
16         0.0        1.0        0.0       0       1       0        1
17         0.0        1.0        0.0       0       1       0        1
18         1.0        0.0        0.0       1       0       0        1
19         0.0        1.0        0.0       0       1       0        1
20         1.0        0.0        0.0       1       0       0        1
21         0.0        1.0        0.0       0       1       0        1
22         0.0        0.0        1.0       0       1       0        0
23         0.0        0.0        1.0       0       0       1        1
24         0.0        0.0        1.0       0       0       1        1
25         0.0        0.0        1.0       0       0       1        1
26         0.0        1.0        0.0       0       1       0        1
27         0.0        1.0        0.0       0       1       0        1
28         0.0        1.0        0.0       0       1       0        1
29         1.0        0.0        0.0       1       0       0        1
..         ...        ...        ...     ...     ...     ...      ...
77         0.0        0.0        1.0       0       0       1        1
78         0.0        1.0        0.0       0       1       0        1
79         0.0        0.0        1.0       0       1       0        0
80         1.0        0.0        0.0       1       0       0        1
81         0.0        0.0        1.0       0       1       0        0
82         1.0        0.0        0.0       1       0       0        1
83         1.0        0.0        0.0       1       0       0        1
84         0.0        1.0        0.0       0       1       0        1
85         1.0        0.0        0.0       1       0       0        1
86         1.0        0.0        0.0       1       0       0        1
87         0.0        0.0        1.0       0       0       1        1
88         0.0        1.0        0.0       0       1       0        1
89         0.0        1.0        0.0       0       1       0        1
90         0.0        1.0        0.0       0       1       0        1
91         1.0        0.0        0.0       1       0       0        1
92         0.0        1.0        0.0       0       1       0        1
93         0.0        1.0        0.0       0       1       0        1
94         0.0        1.0        0.0       0       1       0        1
95         0.0        0.0        1.0       0       0       1        1
96         0.0        0.0        1.0       0       0       1        1
97         1.0        0.0        0.0       1       0       0        1
98         0.0        1.0        0.0       0       1       0        1
99         0.0        0.0        1.0       0       0       1        1
100        0.0        0.0        1.0       0       0       1        1
101        0.0        0.0        1.0       0       1       0        0
102        0.0 

In [74]:
actualAsClassNumber = [0]*expectedOutputTest.shape[0]
predictedAsClassNumber = [0]*expectedOutputTest.shape[0]
for i in range(expectedOutputTest.shape[0]):
    actualAsClassNumber[i] = expectedOutputTest[i].tolist().index(1)
    predictedAsClassNumber[i] = predictedClasses[i].tolist().index(1.0)
confusion_matrix(actualAsClassNumber, predictedAsClassNumber)

array([[36,  0,  0],
       [ 0, 38,  5],
       [ 0,  1, 27]])

In [75]:
clf = svm.SVC(kernel='linear', C=1)
expectedOutputSVM = data.loc[:,13]
inputTrain, inputTest, expectedOutputTrain, expectedOutputTest = train_test_split(dataInputs, expectedOutputSVM, train_size = trainPercent/100, random_state=42)
clf.fit(inputTrain, expectedOutputTrain)
accuracy = clf.score(inputTest, expectedOutputTest)
print(accuracy)

0.205607476636


In [76]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.multiclass import OneVsRestClassifier

In [77]:
#SVM One vs all classifier
clf = Pipeline([
    ('clf', OneVsRestClassifier(LinearSVC()))])
model = clf.fit(inputTrain, expectedOutputTrain)
accuracy = clf.score(inputTest, expectedOutputTest)
print(accuracy)
svmPredicted = model.predict(inputTest)
confusion_matrix(expectedOutputTest,svmPredicted)

0.00934579439252


array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])