In [139]:
import numpy as np
import pandas as pd
import collections
from random import shuffle, randint

from sklearn.cross_validation import train_test_split
from sklearn.metrics import confusion_matrix

In [140]:
#read in csv file
data = pd.read_csv("wine.csv", header=None)
trainPercent = 30 #must be between 0 and 100
lmbda = .00001
numberRowsOfClass1 = 59
numberRowsOfClass2 = 71
numberRowsOfClass3 = 48
data.head() #look at first 5 rows of the data

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [141]:
#Grab desired inputs to test one. Build a dataframe from them.
dataInputs= data.loc[:,1:13]
dataInputs.head()

1     2     3     4    5     6     7     8     9     10    11    12  \
0  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [142]:
#Grab the expected outputs. (This is supervised learning)
y1=[]
y2=[]
y3=[]
for i in range(0,numberRowsOfClass1):
    y1.append([1,0,0]);#class1
for j in range(0, numberRowsOfClass2):
    y2.append([0,1,0]);#class2
for k in range(0, numberRowsOfClass3):
    y3.append([0,0,1]);#Class3
expectedOutput=np.concatenate([y1,y2,y3])
expectedOutput

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1,

In [143]:
#Hint: use train_test_split
inputTrain, inputTest, expectedOutputTrain, expectedOutputTest = train_test_split(dataInputs, expectedOutput, train_size = trainPercent/100)

#inputTest.head()
print(inputTrain.shape)
print(expectedOutputTrain.shape)
print(inputTest.shape)
print(expectedOutputTest.shape)
d = collections.OrderedDict()
for a in expectedOutputTest:
    t = tuple(a)
    if t in d:
        d[t] += 1
    else:
        d[t] = 1

result = []
for (key, value) in d.items():
    result.append(list(key) + [value])

B = np.asarray(result)
print(B)
for Bi in B:
    if Bi[0] == 1:
        class1Total = Bi[3]
    elif Bi[1] == 1:
        class2Total = Bi[3]
    elif Bi[2] == 1:
        class3Total = Bi[3]
    
print(class1Total)
print(class2Total)
print(class3Total)

(53, 13)
(53, 3)
(125, 13)
(125, 3)
[[ 0  0  1 35]
 [ 0  1  0 52]
 [ 1  0  0 38]]
38
52
35


In [144]:
#Build our least squares classifier for 2 classes
D = inputTrain.shape[1] + 1 #num of attributes, +1 is for the intercept (column of 1s)
K = expectedOutput.shape[1]

In [145]:
expectedOutputTrain = np.asarray(expectedOutputTrain)
expectedOutputTest = np.asarray(expectedOutputTest)
inputTrain = np.asarray(inputTrain)
inputTest = np.asarray(inputTest)
p = np.append(1, inputTrain[0])
p.shape
p.reshape(1,D)

array([[  1.00000000e+00,   1.14600000e+01,   3.74000000e+00,
          1.82000000e+00,   1.95000000e+01,   1.07000000e+02,
          3.18000000e+00,   2.58000000e+00,   2.40000000e-01,
          3.58000000e+00,   2.90000000e+00,   7.50000000e-01,
          2.81000000e+00,   5.62000000e+02]])

In [146]:
sum1 = 0
sum2 = 0
numRows = inputTrain.shape[0]
new_col = np.ones((numRows,1))
x = np.c_[new_col, inputTrain]
sum1 = np.dot(x.T, x) + lmbda
sum2 = np.dot(x.T, expectedOutputTrain)
print(sum1)
print(sum2)

[[  5.30000100e+01   6.90970010e+02   1.32360010e+02   1.24200010e+02
    1.01820001e+03   5.28800001e+03   1.23350010e+02   1.11520010e+02
    1.83600100e+01   8.99400100e+01   2.57990010e+02   5.15000100e+01
    1.41700010e+02   4.03750000e+04]
 [  6.90970010e+02   9.03776351e+03   1.73077431e+03   1.62365191e+03
    1.32371670e+04   6.90518800e+04   1.61446191e+03   1.46471201e+03
    2.38679110e+02   1.17119291e+03   3.41129851e+03   6.71313210e+02
    1.85072411e+03   5.34767290e+05]
 [  1.32360010e+02   1.73077431e+03   4.03346010e+02   3.11183210e+02
    2.57807301e+03   1.30474900e+04   2.95625010e+02   2.48931310e+02
    4.87030100e+01   2.13196110e+02   6.72117910e+02   1.20798310e+02
    3.36973510e+02   9.58680000e+04]
 [  1.24200010e+02   1.62365191e+03   3.11183210e+02   2.95135610e+02
    2.40763701e+03   1.24213300e+04   2.90300110e+02   2.63135810e+02
    4.34826100e+01   2.09029710e+02   6.12544210e+02   1.21115710e+02
    3.32301510e+02   9.59180000e+04]
 [  1.018200

In [147]:
W= np.dot(np.linalg.inv(sum1), sum2)
#W = np.array(W)[np.newaxis]
W

array([[ -2.09577622e+00,   2.84313407e+00,   2.52504448e-01],
       [  9.00490166e-02,  -1.38361721e-01,   4.83231113e-02],
       [  1.46733533e-02,  -9.58245766e-03,  -5.09209255e-03],
       [  4.01819773e-01,  -6.84239565e-01,   2.82409143e-01],
       [ -2.09364716e-02,   2.50206478e-02,  -4.08253666e-03],
       [  1.57483446e-03,  -1.61432529e-03,   3.95900454e-05],
       [ -5.17618069e-02,  -1.27311191e-01,   1.79074795e-01],
       [  1.74287279e-01,   1.54764384e-01,  -3.29053848e-01],
       [ -1.81608805e-01,   5.97292252e-01,  -4.15696625e-01],
       [ -3.23546645e-02,   6.90517715e-02,  -3.66953351e-02],
       [ -1.94874680e-02,  -2.72857038e-02,   4.67724957e-02],
       [ -5.26888233e-01,   8.62644369e-01,  -3.35762240e-01],
       [  2.01047071e-01,   1.09451857e-02,  -2.11990692e-01],
       [  6.90109343e-04,  -6.05347284e-04,  -8.47681031e-05]])

In [148]:
#testing
total = expectedOutputTest.shape[0]
predicted = np.zeros((total, K))
i=0
class1Correct=class2Correct=virginicaCorrect=class3Correct=0
correctPredictionCol = [0]*total

In [149]:
for i in range(total):
    x = inputTest[i]    
    x = np.append(1,x)
    x = x.reshape(1,D)
    values = np.dot(W.T,x.T)
    values = values.T
    values = values.flatten()
    maxIndex = np.argmax(values)
    if expectedOutputTest[i][maxIndex] == 1:
        if maxIndex == 0:
            class1Correct += 1
        elif maxIndex == 1:
            class2Correct += 1
        elif maxIndex == 2:
            class3Correct += 1
        correctPredictionCol[i] = 1
    predicted[i][maxIndex] = 1
totalCorrect = class1Correct + class2Correct + class3Correct
print(totalCorrect)
totalAccuracy=totalCorrect/float(total)*100
class1Accuracy = class1Correct/float(class1Total)*100
class2Accuracy = class2Correct/float(class2Total)*100
class3Accuracy = class3Correct/float(class3Total)*100
print("class1 misclassification error = ", 100 - class1Accuracy)
print("class2 misclassification error = ", 100 - class2Accuracy)
print("class3 misclassification error = ", 100 - class3Accuracy)
print("total misclassification error = ", 100 - totalAccuracy)
print(total)

118
class1 misclassification error =  0.0
class2 misclassification error =  13.461538461538453
class3 misclassification error =  0.0
total misclassification error =  5.6000000000000085
125
