In [194]:
import numpy as np
import pandas as pd
import collections
from random import shuffle, randint

from sklearn.cross_validation import train_test_split
from sklearn.metrics import confusion_matrix

In [195]:
#read in csv file
data = pd.read_csv("wine.csv", header=None)
trainPercent = 40 #must be between 0 and 100
lmbda = .00001
numberRowsOfClass1 = 59
numberRowsOfClass2 = 71
numberRowsOfClass3 = 48
data.head() #look at first 5 rows of the data

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [196]:
#Grab desired inputs to test one. Build a dataframe from them.
dataInputs= data.loc[:,1:13]
dataInputs.head()

1     2     3     4    5     6     7     8     9     10    11    12  \
0  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [197]:
#Grab the expected outputs. (This is supervised learning)
y1=[]
y2=[]
y3=[]
for i in range(0,numberRowsOfClass1):
    y1.append([1,0,0]);#class1
for j in range(0, numberRowsOfClass2):
    y2.append([0,1,0]);#class2
for k in range(0, numberRowsOfClass3):
    y3.append([0,0,1]);#Class3
expectedOutput=np.concatenate([y1,y2,y3])
expectedOutput

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1,

In [198]:
#Hint: use train_test_split
inputTrain, inputTest, expectedOutputTrain, expectedOutputTest = train_test_split(dataInputs, expectedOutput, train_size = trainPercent/100)

#inputTest.head()
print(inputTrain.shape)
print(expectedOutputTrain.shape)
print(inputTest.shape)
print(expectedOutputTest.shape)
d = collections.OrderedDict()
for a in expectedOutputTest:
    t = tuple(a)
    if t in d:
        d[t] += 1
    else:
        d[t] = 1

result = []
for (key, value) in d.items():
    result.append(list(key) + [value])

B = np.asarray(result)
print(B)
for Bi in B:
    if Bi[0] == 1:
        class1Total = Bi[3]
    elif Bi[1] == 1:
        class2Total = Bi[3]
    elif Bi[2] == 1:
        class3Total = Bi[3]
    
print(class1Total)
print(class2Total)
print(class3Total)

(71, 13)
(71, 3)
(107, 13)
(107, 3)
[[ 0  1  0 40]
 [ 0  0  1 29]
 [ 1  0  0 38]]
38
40
29


In [199]:
#Build our least squares classifier for 2 classes
D = inputTrain.shape[1] + 1 #num of attributes, +1 is for the intercept (column of 1s)
K = expectedOutput.shape[1]

In [200]:
expectedOutputTrain = np.asarray(expectedOutputTrain)
expectedOutputTest = np.asarray(expectedOutputTest)
inputTrain = np.asarray(inputTrain)
inputTest = np.asarray(inputTest)
p = np.append(1, inputTrain[0])
p.shape
p.reshape(1,D)

array([[  1.00000000e+00,   1.23700000e+01,   1.13000000e+00,
          2.16000000e+00,   1.90000000e+01,   8.70000000e+01,
          3.50000000e+00,   3.10000000e+00,   1.90000000e-01,
          1.87000000e+00,   4.45000000e+00,   1.22000000e+00,
          2.87000000e+00,   4.20000000e+02]])

In [201]:
sum1 = 0
sum2 = 0
numRows = inputTrain.shape[0]
new_col = np.ones((numRows,1))
x = np.c_[new_col, inputTrain]
sum1 = np.dot(x.T, x) + lmbda
sum2 = np.dot(x.T, expectedOutputTrain)
print(sum1)
print(sum2)

[[  7.10000100e+01   9.17580010e+02   1.60750010e+02   1.66000010e+02
    1.36970001e+03   7.03800001e+03   1.60930010e+02   1.44280010e+02
    2.44100100e+01   1.15200010e+02   3.69950010e+02   6.75600100e+01
    1.83460010e+02   4.99840000e+04]
 [  9.17580010e+02   1.19049484e+04   2.09018971e+03   2.14750081e+03
    1.76427470e+04   9.11377800e+04   2.09212531e+03   1.87780731e+03
    3.14976810e+02   1.49810501e+03   4.86098971e+03   8.71249210e+02
    2.37177681e+03   6.56919910e+05]
 [  1.60750010e+02   2.09018971e+03   4.48075110e+02   3.81893910e+02
    3.17015401e+03   1.60621200e+04   3.49115910e+02   2.99264910e+02
    5.77143100e+01   2.47132310e+02   8.92229510e+02   1.44975010e+02
    4.00226010e+02   1.12685240e+05]
 [  1.66000010e+02   2.14750081e+03   3.81893910e+02   3.94418210e+02
    3.24855101e+03   1.65663000e+04   3.77346910e+02   3.39454210e+02
    5.76798100e+01   2.70512110e+02   8.83039810e+02   1.57090010e+02
    4.27837910e+02   1.18051030e+05]
 [  1.369700

In [202]:
W= np.dot(np.linalg.inv(sum1), sum2)
#W = np.array(W)[np.newaxis]
W

array([[ -2.68149903e+00,   3.55262198e+00,   1.28774330e-01],
       [  1.68662040e-01,  -2.23414013e-01,   5.47592199e-02],
       [  4.48128664e-02,  -6.13587464e-02,   1.65449527e-02],
       [  2.63943018e-01,  -4.43047178e-01,   1.79103180e-01],
       [ -3.19305652e-02,   3.49780887e-02,  -3.04667861e-03],
       [ -1.10929599e-04,   8.64028645e-04,  -7.53005805e-04],
       [ -8.01471207e-02,   2.23333236e-02,   5.78139246e-02],
       [  1.32957485e-01,   3.41501469e-02,  -1.67109297e-01],
       [ -1.06172741e-01,   1.64627383e-01,  -5.84669423e-02],
       [ -2.73582736e-02,   1.34301194e-01,  -1.06943530e-01],
       [ -1.84479620e-02,  -4.38680881e-02,   6.23151250e-02],
       [ -2.06136061e-02,   4.32507255e-01,  -4.11890293e-01],
       [  1.46702480e-01,  -1.39726024e-02,  -1.32728988e-01],
       [  6.17899906e-04,  -5.05288738e-04,  -1.12617674e-04]])

In [203]:
#testing
total = expectedOutputTest.shape[0]
predicted = np.zeros((total, K))
i=0
class1Correct=class2Correct=totalCorrect=class3Correct=0
correctPredictionCol = [0]*total

In [204]:
for i in range(total):
    x = inputTest[i]    
    x = np.append(1,x)
    x = x.reshape(1,D)
    values = np.dot(W.T,x.T)
    values = values.T
    values = values.flatten()
    maxIndex = np.argmax(values)
    if expectedOutputTest[i][maxIndex] == 1:
        if maxIndex == 0:
            class1Correct += 1
        elif maxIndex == 1:
            class2Correct += 1
        elif maxIndex == 2:
            class3Correct += 1
        correctPredictionCol[i] = 1
    predicted[i][maxIndex] = 1
totalCorrect = class1Correct + class2Correct + class3Correct
print(totalCorrect)
totalAccuracy=totalCorrect/float(total)*100
class1Accuracy = class1Correct/float(class1Total)*100
class2Accuracy = class2Correct/float(class2Total)*100
class3Accuracy = class3Correct/float(class3Total)*100
print("class1 misclassification error = ", 100 - class1Accuracy)
print("class2 misclassification error = ", 100 - class2Accuracy)
print("class3 misclassification error = ", 100 - class3Accuracy)
print("total misclassification error = ", 100 - totalAccuracy)
print(total)

105
class1 misclassification error =  0.0
class2 misclassification error =  5.0
class3 misclassification error =  0.0
total misclassification error =  1.8691588785046775
107
