In [205]:
import numpy as np
import pandas as pd
import collections
from random import shuffle, randint

from sklearn.cross_validation import train_test_split
from sklearn.metrics import confusion_matrix

In [206]:
#read in csv file
data = pd.read_csv("wine.csv", header=None)
trainPercent = 40 #must be between 0 and 100
lmbda = .00001
numberRowsOfClass1 = 59
numberRowsOfClass2 = 71
numberRowsOfClass3 = 48
data.head() #look at first 5 rows of the data

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [207]:
#Grab desired inputs to test one. Build a dataframe from them.
dataInputs= data.loc[:,1:13]
dataInputs.head()

1     2     3     4    5     6     7     8     9     10    11    12  \
0  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [208]:
#Grab the expected outputs. (This is supervised learning)
y1=[]
y2=[]
y3=[]
for i in range(0,numberRowsOfClass1):
    y1.append([1,0,0]);#class1
for j in range(0, numberRowsOfClass2):
    y2.append([0,1,0]);#class2
for k in range(0, numberRowsOfClass3):
    y3.append([0,0,1]);#Class3
expectedOutput=np.concatenate([y1,y2,y3])
expectedOutput

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1,

In [209]:
#Hint: use train_test_split
inputTrain, inputTest, expectedOutputTrain, expectedOutputTest = train_test_split(dataInputs, expectedOutput, train_size = trainPercent/100)

#inputTest.head()
print(inputTrain.shape)
print(expectedOutputTrain.shape)
print(inputTest.shape)
print(expectedOutputTest.shape)
d = collections.OrderedDict()
for a in expectedOutputTest:
    t = tuple(a)
    if t in d:
        d[t] += 1
    else:
        d[t] = 1

result = []
for (key, value) in d.items():
    result.append(list(key) + [value])

B = np.asarray(result)
print(B)
for Bi in B:
    if Bi[0] == 1:
        class1Total = Bi[3]
    elif Bi[1] == 1:
        class2Total = Bi[3]
    elif Bi[2] == 1:
        class3Total = Bi[3]
    
print(class1Total)
print(class2Total)
print(class3Total)

(71, 13)
(71, 3)
(107, 13)
(107, 3)
[[ 0  0  1 31]
 [ 1  0  0 36]
 [ 0  1  0 40]]
36
40
31


In [210]:
#Build our least squares classifier for 2 classes
D = inputTrain.shape[1] + 1 #num of attributes, +1 is for the intercept (column of 1s)
K = expectedOutput.shape[1]

In [211]:
expectedOutputTrain = np.asarray(expectedOutputTrain)
expectedOutputTest = np.asarray(expectedOutputTest)
inputTrain = np.asarray(inputTrain)
inputTest = np.asarray(inputTest)
p = np.append(1, inputTrain[0])
p.shape
p.reshape(1,D)

array([[  1.00000000e+00,   1.31600000e+01,   2.36000000e+00,
          2.67000000e+00,   1.86000000e+01,   1.01000000e+02,
          2.80000000e+00,   3.24000000e+00,   3.00000000e-01,
          2.81000000e+00,   5.68000000e+00,   1.03000000e+00,
          3.17000000e+00,   1.18500000e+03]])

In [212]:
sum1 = 0
sum2 = 0
numRows = inputTrain.shape[0]
new_col = np.ones((numRows,1))
x = np.c_[new_col, inputTrain]
sum1 = np.dot(x.T, x) + lmbda
sum2 = np.dot(x.T, expectedOutputTrain)
print(sum1)
print(sum2)

[[  7.10000100e+01   9.24170010e+02   1.67230010e+02   1.66890010e+02
    1.37700001e+03   7.14700001e+03   1.67850010e+02   1.50940010e+02
    2.52500100e+01   1.19650010e+02   3.46600010e+02   6.80700100e+01
    1.91040010e+02   5.32010000e+04]
 [  9.24170010e+02   1.20821427e+04   2.18027581e+03   2.17444441e+03
    1.78252900e+04   9.33074800e+04   2.19789341e+03   1.98408581e+03
    3.27643210e+02   1.56397881e+03   4.58262621e+03   8.86786410e+02
    2.48986851e+03   7.05244920e+05]
 [  1.67230010e+02   2.18027581e+03   4.79717110e+02   3.98412010e+02
    3.31594901e+03   1.68743100e+04   3.77738910e+02   3.22552510e+02
    6.21349100e+01   2.68676210e+02   8.53245110e+02   1.51003510e+02
    4.27597210e+02   1.21932860e+05]
 [  1.66890010e+02   2.17444441e+03   3.98412010e+02   3.96507310e+02
    3.25732201e+03   1.68761900e+04   3.94696710e+02   3.54610010e+02
    5.96954100e+01   2.81004510e+02   8.22565610e+02   1.59225110e+02
    4.47013110e+02   1.26186920e+05]
 [  1.377000

In [213]:
W= np.dot(np.linalg.inv(sum1), sum2)
#W = np.array(W)[np.newaxis]
W

array([[ -2.84970046e+00,   3.38172419e+00,   4.67899289e-01],
       [  1.61506993e-01,  -1.81998277e-01,   2.04966495e-02],
       [  2.41877064e-02,  -1.17301732e-01,   9.31133981e-02],
       [  2.27459336e-01,  -2.22078382e-01,  -5.37935930e-03],
       [ -3.38352767e-02,   2.52716149e-02,   8.56421655e-03],
       [  3.29232760e-03,  -1.19380277e-04,  -3.17293728e-03],
       [ -1.55128911e-01,   1.49322763e-02,   1.40198432e-01],
       [  2.06928515e-01,   6.95698283e-02,  -2.76500774e-01],
       [  4.09365871e-01,   5.56078689e-02,  -4.64981573e-01],
       [ -1.55123900e-02,  -3.61010210e-03,   1.91235883e-02],
       [ -5.88469639e-03,  -6.39861718e-02,   6.98703246e-02],
       [ -1.70481680e-01,   1.94444385e-01,  -2.39627457e-02],
       [  1.68036184e-01,   1.47254259e-02,  -1.82761081e-01],
       [  4.69746913e-04,  -4.89138265e-04,   1.93861273e-05]])

In [214]:
#testing
total = expectedOutputTest.shape[0]
predicted = np.zeros((total, K))
i=0
class1Correct=class2Correct=totalCorrect=class3Correct=0
correctPredictionCol = [0]*total

In [215]:
for i in range(total):
    x = inputTest[i]    
    x = np.append(1,x)
    x = x.reshape(1,D)
    values = np.dot(W.T,x.T)
    values = values.T
    values = values.flatten()
    maxIndex = np.argmax(values)
    if expectedOutputTest[i][maxIndex] == 1:
        if maxIndex == 0:
            class1Correct += 1
        elif maxIndex == 1:
            class2Correct += 1
        elif maxIndex == 2:
            class3Correct += 1
        correctPredictionCol[i] = 1
    predicted[i][maxIndex] = 1
totalCorrect = class1Correct + class2Correct + class3Correct
print(totalCorrect)
totalAccuracy=totalCorrect/float(total)*100
class1Accuracy = class1Correct/float(class1Total)*100
class2Accuracy = class2Correct/float(class2Total)*100
class3Accuracy = class3Correct/float(class3Total)*100
print("class1 misclassification error = ", 100 - class1Accuracy)
print("class2 misclassification error = ", 100 - class2Accuracy)
print("class3 misclassification error = ", 100 - class3Accuracy)
print("total misclassification error = ", 100 - totalAccuracy)
print(total)

105
class1 misclassification error =  0.0
class2 misclassification error =  2.5
class3 misclassification error =  3.225806451612897
total misclassification error =  1.8691588785046775
107
