In [34]:
import numpy as np
import pandas as pd
import collections
from random import shuffle, randint

from sklearn.cross_validation import train_test_split
from sklearn.metrics import confusion_matrix

In [35]:
#read in csv file
data = pd.read_csv("wine.csv", header=None)
trainPercent = 40 #must be between 0 and 100
lmbda = .00001
numberRowsOfClass1 = 59
numberRowsOfClass2 = 71
numberRowsOfClass3 = 48
data.head() #look at first 5 rows of the data

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [36]:
#Grab desired inputs to test one. Build a dataframe from them.
dataInputs= data.loc[:,1:13]
dataInputs.head()

1     2     3     4    5     6     7     8     9     10    11    12  \
0  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [37]:
#Grab the expected outputs. (This is supervised learning)
y1=[]
y2=[]
y3=[]
for i in range(0,numberRowsOfClass1):
    y1.append([1,0,0]);#class1
for j in range(0, numberRowsOfClass2):
    y2.append([0,1,0]);#class2
for k in range(0, numberRowsOfClass3):
    y3.append([0,0,1]);#Class3
expectedOutput=np.concatenate([y1,y2,y3])
expectedOutput

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1,

In [38]:
#Hint: use train_test_split
inputTrain, inputTest, expectedOutputTrain, expectedOutputTest = train_test_split(dataInputs, expectedOutput, train_size = trainPercent/100)

#inputTest.head()
print(inputTrain.shape)
print(expectedOutputTrain.shape)
print(inputTest.shape)
print(expectedOutputTest.shape)
d = collections.OrderedDict()
for a in expectedOutputTest:
    t = tuple(a)
    if t in d:
        d[t] += 1
    else:
        d[t] = 1

result = []
for (key, value) in d.items():
    result.append(list(key) + [value])

B = np.asarray(result)
print(B)
for Bi in B:
    if Bi[0] == 1:
        class1Total = Bi[3]
    elif Bi[1] == 1:
        class2Total = Bi[3]
    elif Bi[2] == 1:
        class3Total = Bi[3]
    
print(class1Total)
print(class2Total)
print(class3Total)

(71, 13)
(71, 3)
(107, 13)
(107, 3)
[[ 0  0  1 27]
 [ 1  0  0 36]
 [ 0  1  0 44]]
36
44
27


In [39]:
#Build our least squares classifier for 2 classes
D = inputTrain.shape[1] + 1 #num of attributes, +1 is for the intercept (column of 1s)
K = expectedOutput.shape[1]

In [40]:
expectedOutputTrain = np.asarray(expectedOutputTrain)
expectedOutputTest = np.asarray(expectedOutputTest)
inputTrain = np.asarray(inputTrain)
inputTest = np.asarray(inputTest)
p = np.append(1, inputTrain[0])
p.shape
p.reshape(1,D)

array([[  1.00000000e+00,   1.18400000e+01,   8.90000000e-01,
          2.58000000e+00,   1.80000000e+01,   9.40000000e+01,
          2.20000000e+00,   2.21000000e+00,   2.20000000e-01,
          2.35000000e+00,   3.05000000e+00,   7.90000000e-01,
          3.08000000e+00,   5.20000000e+02]])

In [41]:
sum1 = 0
sum2 = 0
numRows = inputTrain.shape[0]
new_col = np.ones((numRows,1))
x = np.c_[new_col, inputTrain]
sum1 = np.dot(x.T, x) + lmbda
sum2 = np.dot(x.T, expectedOutputTrain)
print(sum1)
print(sum2)

[[  7.10000100e+01   9.28120010e+02   1.76840010e+02   1.71220010e+02
    1.40680001e+03   7.11200001e+03   1.62460010e+02   1.40810010e+02
    2.66500100e+01   1.11630010e+02   3.68760010e+02   6.42060100e+01
    1.81100010e+02   5.38490000e+04]
 [  9.28120010e+02   1.21756422e+04   2.30312431e+03   2.24131471e+03
    1.83562250e+04   9.31801400e+04   2.13764511e+03   1.85721831e+03
    3.46338010e+02   1.46311631e+03   4.89612671e+03   8.39881650e+02
    2.37213991e+03   7.14354410e+05]
 [  1.76840010e+02   2.30312431e+03   5.26447410e+02   4.29352610e+02
    3.59814301e+03   1.74293600e+04   3.83572810e+02   3.09824010e+02
    7.12584100e+01   2.62716710e+02   9.39839310e+02   1.51310870e+02
    4.28052210e+02   1.24594170e+05]
 [  1.71220010e+02   2.24131471e+03   4.29352610e+02   4.16589210e+02
    3.41495101e+03   1.71759400e+04   3.93223310e+02   3.40087510e+02
    6.45670100e+01   2.68843810e+02   9.01293910e+02   1.54492870e+02
    4.35870010e+02   1.30519650e+05]
 [  1.406800

In [42]:
W= np.dot(np.linalg.inv(sum1), sum2)
#W = np.array(W)[np.newaxis]
W

array([[ -1.94433494e+00,   3.29459515e+00,  -3.50335543e-01],
       [  1.22094756e-01,  -1.46558168e-01,   2.44691288e-02],
       [  2.61788562e-02,  -1.09049367e-01,   8.28705990e-02],
       [  1.56107379e-01,  -5.58884223e-01,   4.02778934e-01],
       [ -2.19929617e-02,   2.73745028e-02,  -5.38130693e-03],
       [ -1.05913137e-03,   6.31922976e-04,   4.27253687e-04],
       [ -1.46266024e-01,   5.32847833e-02,   9.29819518e-02],
       [  2.59514816e-01,   1.11092642e-01,  -3.70609083e-01],
       [  6.66503615e-02,   6.81547614e-01,  -7.48203037e-01],
       [ -9.24685311e-02,   4.78378497e-02,   4.46319126e-02],
       [  9.52674902e-03,  -6.45251969e-02,   5.49971533e-02],
       [ -1.21270761e-01,   2.22135174e-01,  -1.00867682e-01],
       [  8.83091662e-02,  -8.27184865e-03,  -8.00375109e-02],
       [  7.22201746e-04,  -6.62853822e-04,  -5.93508722e-05]])

In [43]:
#testing
total = expectedOutputTest.shape[0]
predicted = np.zeros((total, K))
i=0
class1Correct=class2Correct=totalCorrect=class3Correct=0
correctPredictionCol = [0]*total

In [44]:
print(inputTest)
for i in range(total):
    x = inputTest[i]    
    x = np.append(1,x)    
    x = x.reshape(1,D)    
    values = np.dot(W.T,x.T)
    values = values.T
    values = values.flatten()
    maxIndex = np.argmax(values)
    if expectedOutputTest[i][maxIndex] == 1:
        if maxIndex == 0:
            class1Correct += 1
        elif maxIndex == 1:
            class2Correct += 1
        elif maxIndex == 2:
            class3Correct += 1
        correctPredictionCol[i] = 1
    predicted[i][maxIndex] = 1
totalCorrect = class1Correct + class2Correct + class3Correct
print(totalCorrect)
totalAccuracy=totalCorrect/float(total)*100
class1Accuracy = class1Correct/float(class1Total)*100
class2Accuracy = class2Correct/float(class2Total)*100
class3Accuracy = class3Correct/float(class3Total)*100
print("class1 misclassification error = ", 100 - class1Accuracy)
print("class2 misclassification error = ", 100 - class2Accuracy)
print("class3 misclassification error = ", 100 - class3Accuracy)
print("total misclassification error = ", 100 - totalAccuracy)
print(total)

[[  1.36200000e+01   4.95000000e+00   2.35000000e+00 ...,   9.10000000e-01
    2.05000000e+00   5.50000000e+02]
 [  1.33600000e+01   2.56000000e+00   2.35000000e+00 ...,   7.00000000e-01
    2.47000000e+00   7.80000000e+02]
 [  1.27700000e+01   2.39000000e+00   2.28000000e+00 ...,   5.70000000e-01
    1.63000000e+00   4.70000000e+02]
 ..., 
 [  1.27900000e+01   2.67000000e+00   2.48000000e+00 ...,   4.80000000e-01
    1.47000000e+00   4.80000000e+02]
 [  1.34100000e+01   3.84000000e+00   2.12000000e+00 ...,   9.10000000e-01
    3.00000000e+00   1.03500000e+03]
 [  1.35000000e+01   1.81000000e+00   2.61000000e+00 ...,   1.12000000e+00
    3.82000000e+00   8.45000000e+02]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class '